[phases.setup]
aptPkgs = [
    "libglib2.0-0",
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libpangoft2-1.0-0",
    "libcairo2",
    "libgdk-pixbuf-2.0-0",
    "libharfbuzz0b",
    "libfontconfig1",
    "python3-dev",
    "gcc",
    "g++",
    "libc-dev",
    "libffi-dev",
    "zlib1g-dev",
    "libjpeg-dev",
    "libopenjp2-7-dev",
    "libwebp-dev"
]
cmds = [
    "apt-get update && apt-get install -y --no-install-recommends $NIXPACKS_APT_PKGS",
    "ldconfig"
]

[phases.build]
cmds = [
    "pip install --no-binary weasyprint -r requirements.txt",
    "ldconfig -p | grep libgobject || echo 'libgobject not found'",
    "python test_weasyprint.py"
]

[start]
cmd = "export LD_LIBRARY_PATH=/usr/lib:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH && gunicorn app:app"