[phases.setup]
aptPkgs = [
    "libpango-1.0-0",
    "libpangocairo-1.0-0",
    "libpangoft2-1.0-0",
    "libcairo2",
    "libgdk-pixbuf2.0-0",
    "libffi-dev"
]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app"